version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: resumedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8698:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@db:5432/resumedb
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/.env:/app/.env

volumes:
  postgres_data: